*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 11.02.2022 at 19:06:44
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZAPV_CATEGORIES.................................*
FORM GET_DATA_ZAPV_CATEGORIES.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZAP_CATEGORIES WHERE
(VIM_WHERETAB) .
    CLEAR ZAPV_CATEGORIES .
ZAPV_CATEGORIES-MANDT =
ZAP_CATEGORIES-MANDT .
ZAPV_CATEGORIES-CATEGORY_ID =
ZAP_CATEGORIES-CATEGORY_ID .
ZAPV_CATEGORIES-CATEGORY_NAME =
ZAP_CATEGORIES-CATEGORY_NAME .
ZAPV_CATEGORIES-DESCRIPTION =
ZAP_CATEGORIES-DESCRIPTION .
<VIM_TOTAL_STRUC> = ZAPV_CATEGORIES.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZAPV_CATEGORIES .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZAPV_CATEGORIES.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZAPV_CATEGORIES-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZAP_CATEGORIES WHERE
  CATEGORY_ID = ZAPV_CATEGORIES-CATEGORY_ID .
    IF SY-SUBRC = 0.
    DELETE ZAP_CATEGORIES .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZAP_CATEGORIES WHERE
  CATEGORY_ID = ZAPV_CATEGORIES-CATEGORY_ID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZAP_CATEGORIES.
    ENDIF.
ZAP_CATEGORIES-MANDT =
ZAPV_CATEGORIES-MANDT .
ZAP_CATEGORIES-CATEGORY_ID =
ZAPV_CATEGORIES-CATEGORY_ID .
ZAP_CATEGORIES-CATEGORY_NAME =
ZAPV_CATEGORIES-CATEGORY_NAME .
ZAP_CATEGORIES-DESCRIPTION =
ZAPV_CATEGORIES-DESCRIPTION .
    IF SY-SUBRC = 0.
    UPDATE ZAP_CATEGORIES .
    ELSE.
    INSERT ZAP_CATEGORIES .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZAPV_CATEGORIES-UPD_FLAG,
STATUS_ZAPV_CATEGORIES-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZAPV_CATEGORIES.
  SELECT SINGLE * FROM ZAP_CATEGORIES WHERE
CATEGORY_ID = ZAPV_CATEGORIES-CATEGORY_ID .
ZAPV_CATEGORIES-MANDT =
ZAP_CATEGORIES-MANDT .
ZAPV_CATEGORIES-CATEGORY_ID =
ZAP_CATEGORIES-CATEGORY_ID .
ZAPV_CATEGORIES-CATEGORY_NAME =
ZAP_CATEGORIES-CATEGORY_NAME .
ZAPV_CATEGORIES-DESCRIPTION =
ZAP_CATEGORIES-DESCRIPTION .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZAPV_CATEGORIES USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZAPV_CATEGORIES-CATEGORY_ID TO
ZAP_CATEGORIES-CATEGORY_ID .
MOVE ZAPV_CATEGORIES-MANDT TO
ZAP_CATEGORIES-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZAP_CATEGORIES'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZAP_CATEGORIES TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZAP_CATEGORIES'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
