*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 11.02.2022 at 19:07:35
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZAPV_PRODUCTS...................................*
FORM GET_DATA_ZAPV_PRODUCTS.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZAP_PRODUCTS WHERE
(VIM_WHERETAB) .
    CLEAR ZAPV_PRODUCTS .
ZAPV_PRODUCTS-MANDT =
ZAP_PRODUCTS-MANDT .
ZAPV_PRODUCTS-PRODUCT_ID =
ZAP_PRODUCTS-PRODUCT_ID .
ZAPV_PRODUCTS-PRODUCT_NAME =
ZAP_PRODUCTS-PRODUCT_NAME .
ZAPV_PRODUCTS-SUPPLIER_ID =
ZAP_PRODUCTS-SUPPLIER_ID .
ZAPV_PRODUCTS-CATEGORY_ID =
ZAP_PRODUCTS-CATEGORY_ID .
ZAPV_PRODUCTS-UNIT_PRICE =
ZAP_PRODUCTS-UNIT_PRICE .
<VIM_TOTAL_STRUC> = ZAPV_PRODUCTS.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZAPV_PRODUCTS .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZAPV_PRODUCTS.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZAPV_PRODUCTS-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZAP_PRODUCTS WHERE
  PRODUCT_ID = ZAPV_PRODUCTS-PRODUCT_ID .
    IF SY-SUBRC = 0.
    DELETE ZAP_PRODUCTS .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZAP_PRODUCTS WHERE
  PRODUCT_ID = ZAPV_PRODUCTS-PRODUCT_ID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZAP_PRODUCTS.
    ENDIF.
ZAP_PRODUCTS-MANDT =
ZAPV_PRODUCTS-MANDT .
ZAP_PRODUCTS-PRODUCT_ID =
ZAPV_PRODUCTS-PRODUCT_ID .
ZAP_PRODUCTS-PRODUCT_NAME =
ZAPV_PRODUCTS-PRODUCT_NAME .
ZAP_PRODUCTS-SUPPLIER_ID =
ZAPV_PRODUCTS-SUPPLIER_ID .
ZAP_PRODUCTS-CATEGORY_ID =
ZAPV_PRODUCTS-CATEGORY_ID .
ZAP_PRODUCTS-UNIT_PRICE =
ZAPV_PRODUCTS-UNIT_PRICE .
    IF SY-SUBRC = 0.
    UPDATE ZAP_PRODUCTS .
    ELSE.
    INSERT ZAP_PRODUCTS .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZAPV_PRODUCTS-UPD_FLAG,
STATUS_ZAPV_PRODUCTS-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZAPV_PRODUCTS.
  SELECT SINGLE * FROM ZAP_PRODUCTS WHERE
PRODUCT_ID = ZAPV_PRODUCTS-PRODUCT_ID .
ZAPV_PRODUCTS-MANDT =
ZAP_PRODUCTS-MANDT .
ZAPV_PRODUCTS-PRODUCT_ID =
ZAP_PRODUCTS-PRODUCT_ID .
ZAPV_PRODUCTS-PRODUCT_NAME =
ZAP_PRODUCTS-PRODUCT_NAME .
ZAPV_PRODUCTS-SUPPLIER_ID =
ZAP_PRODUCTS-SUPPLIER_ID .
ZAPV_PRODUCTS-CATEGORY_ID =
ZAP_PRODUCTS-CATEGORY_ID .
ZAPV_PRODUCTS-UNIT_PRICE =
ZAP_PRODUCTS-UNIT_PRICE .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZAPV_PRODUCTS USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZAPV_PRODUCTS-PRODUCT_ID TO
ZAP_PRODUCTS-PRODUCT_ID .
MOVE ZAPV_PRODUCTS-MANDT TO
ZAP_PRODUCTS-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZAP_PRODUCTS'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZAP_PRODUCTS TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZAP_PRODUCTS'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
